[features]
resolution = true
skip-lint = false

[programs.devnet]
farming_idle_program = "9XSbAChRjx7SppoSYxc42rEKTrGS2d66L1e9kkL15AMr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/mikesulistio/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
